flyway:
  enabled: true
  locations: classpath:sql/migration/postgresql
  baseline-on-migrate: true

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/dipegroupdb
    username: dbuser
    password: dbpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

